server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fypdb
spring.datasource.username=sureshuprety
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Zoom Integration
zoom.sdk.key=${ZOOM_SDK_KEY:dummy_key}
zoom.sdk.secret=${ZOOM_SDK_SECRET:dummy_secret}
zoom.account.id=VVeTeU89QaKYtrUvTdp2jQ
zoom.client.id=rLX7CpyaSIntRlwFl3Rag
zoom.client.secret=8do6sJpdU8VvaOtbUdgJPN1WI2Os0oQm
zoom.api.base-url=https://api.zoom.us/v2

# Email Configuration (Sender credentials - The email that Skill Mandala uses to send messages)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# IMPORTANT: Put the email address that generated the App Password below
spring.mail.username=codewithjerry00@gmail.com
spring.mail.password=dtllnhzeufuikwtu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
