server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fypdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sureshuprety}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Zoom Integration
zoom.sdk.key=${ZOOM_SDK_KEY:dummy_key}
zoom.sdk.secret=${ZOOM_SDK_SECRET:dummy_secret}
zoom.account.id=${ZOOM_ACCOUNT_ID:VVeTeU89QaKYtrUvTdp2jQ}
zoom.client.id=${ZOOM_CLIENT_ID:rLX7CpyaSIntRlwFl3Rag}
zoom.client.secret=${ZOOM_CLIENT_SECRET:8do6sJpdU8VvaOtbUdgJPN1WI2Os0oQm}
zoom.api.base-url=https://api.zoom.us/v2
zoom.user.email=${ZOOM_USER_EMAIL:np03cs4a230502@heraldcollege.edu.np}

# JWT Secret
jwt.secret=${JWT_SECRET:SkillMandalaSuperSecretKeySkillMandalaSuperSecretKeySkillMandala123}

# Email Configuration (Sender credentials - The email that Skill Mandala uses to send messages)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# IMPORTANT: Put the email address that generated the App Password below
spring.mail.username=${SPRING_MAIL_USERNAME:codewithjerry00@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:dtllnhzeufuikwtu}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
